# Generated by Django 4.2.30 on 2026-05-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('titulo_academico', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('dedicacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'persona',
                'ordering': ['nombre'],
            },
        ),
    ]
