# Generated by Django 4.2.30 on 2026-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
